### ISSUE TITLE
Email addition

### ISSUE THREAD

**Issue by rie-clickmark** [clickmark/yashima-gumi#1]
iramina＠yashima-gumi.co.jp

**Comment by clickmark** [comment]
iramina@yashima-gumi.co.jp
?782oiqL3

Manual setup
Mail server username
iramina@yashima-gumi.co.jp

Incoming mail server
yashima-gumi.co.jp

Outgoing mail server
yashima-gumi.co.jp
(server requires authentication)

Supported incoming mail protocols
POP3, POP3 over SSL/TLS, IMAP, IMAP over SSL/TLS

Supported outgoing mail protocols
SMTP

To connect via POP3 securely over SSL/TLS, use port 995.

To connect via IMAP securely over SSL/TLS, use port 993.

To send messages via SMTP securely, use port 465.
